In [1]:
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt

In [2]:
IMAGE_SIZE = 256
CHANNELS = 3

In [4]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=10,
        horizontal_flip=True
)
train_generator = train_datagen.flow_from_directory(
        'dataset/train',
        target_size=(IMAGE_SIZE,IMAGE_SIZE),
        batch_size=32,
        class_mode="sparse",
#         save_to_dir="C:\\Code\\potato-disease-classification\\training\\AugmentedImages"
)

Found 1506 images belonging to 3 classes.


In [5]:
train_generator.class_indices

{'Potato___Early_blight': 0, 'Potato___Late_blight': 1, 'Potato___healthy': 2}

In [6]:
class_names = list(train_generator.class_indices.keys())
class_names

['Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy']

In [7]:
count=0
for image_batch, label_batch in train_generator:
#     print(label_batch)
    print(image_batch[0])
    break
#     count+=1
#     if count>2:
#  

[[[0.48467004 0.4258465  0.4376112 ]
  [0.4613449  0.40252137 0.41428608]
  [0.5005855  0.441762   0.4535267 ]
  ...
  [0.565658   0.5029128  0.5068344 ]
  [0.52143294 0.45868784 0.4626094 ]
  [0.4853577  0.4226126  0.42653418]]

 [[0.50485796 0.44603443 0.45779914]
  [0.5091362  0.4503127  0.4620774 ]
  [0.5460207  0.48719713 0.49896184]
  ...
  [0.500624   0.4378789  0.44180048]
  [0.49720985 0.43446475 0.43838632]
  [0.47356802 0.41082293 0.4147445 ]]

 [[0.52996224 0.47113872 0.48290342]
  [0.5622919  0.5034684  0.5152331 ]
  [0.57572967 0.5169061  0.5286708 ]
  ...
  [0.54757917 0.48483405 0.4887556 ]
  [0.5704224  0.5076773  0.5115989 ]
  [0.5206518  0.45790672 0.4618283 ]]

 ...

 [[0.65721905 0.6140818  0.6376112 ]
  [0.6648381  0.6217008  0.64523023]
  [0.6731304  0.62999314 0.65352255]
  ...
  [0.7605717  0.72135603 0.7252776 ]
  [0.75708836 0.7178727  0.72179425]
  [0.7494709  0.7102552  0.7141768 ]]

 [[0.68467003 0.6415328  0.6650622 ]
  [0.6885911  0.6454539  0.6689833 ]


In [8]:
validation_datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=10,
        horizontal_flip=True)
validation_generator = validation_datagen.flow_from_directory(
        'dataset/val',
        target_size=(IMAGE_SIZE,IMAGE_SIZE),
        batch_size=32,
        class_mode="sparse"
)

Found 215 images belonging to 3 classes.


In [9]:
test_datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=10,
        horizontal_flip=True)

test_generator = test_datagen.flow_from_directory(
        'dataset/test',
        target_size=(IMAGE_SIZE,IMAGE_SIZE),
        batch_size=32,
        class_mode="sparse"
)

Found 431 images belonging to 3 classes.


In [10]:
for image_batch, label_batch in test_generator:
    print(image_batch[0])
    break

[[[0.53450906 0.47176397 0.5149012 ]
  [0.5432537  0.48050866 0.5236459 ]
  [0.55407566 0.4913306  0.5344678 ]
  ...
  [0.53057474 0.47959432 0.51881003]
  [0.53103876 0.48005837 0.51927406]
  [0.5315028  0.4805224  0.5197381 ]]

 [[0.533813   0.47106794 0.51420516]
  [0.54278976 0.4800446  0.5231819 ]
  [0.55337965 0.49063453 0.5337718 ]
  ...
  [0.55868727 0.5077069  0.54692256]
  [0.5610074  0.510027   0.5492427 ]
  [0.56332743 0.51234704 0.5515627 ]]

 [[0.533117   0.4703719  0.51350915]
  [0.5423257  0.4795806  0.52271783]
  [0.5526836  0.48993853 0.53307575]
  ...
  [0.567492   0.5165116  0.5557273 ]
  [0.567028   0.5160476  0.5552633 ]
  [0.56656396 0.5155836  0.55479926]]

 ...

 [[0.51413643 0.46315604 0.5023717 ]
  [0.5122803  0.46129993 0.50051564]
  [0.51042426 0.45944384 0.49865952]
  ...
  [0.5879777  0.5605267  0.5879777 ]
  [0.58593696 0.5584859  0.58593696]
  [0.60711294 0.57966197 0.60711294]]

 [[0.4828188  0.43183842 0.4710541 ]
  [0.48096275 0.42998233 0.46919805]


In [11]:
input_shape = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)
n_classes = 3

model = models.Sequential([
    layers.InputLayer(input_shape=input_shape),
    layers.Conv2D(32, kernel_size = (3,3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64,  kernel_size = (3,3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64,  kernel_size = (3,3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(n_classes, activation='softmax'),
])

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 254, 254, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 127, 127, 32)     0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 125, 125, 64)      18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 62, 62, 64)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 60, 60, 64)        36928     
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 30, 30, 64)       0

In [13]:
model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=['accuracy']
)

In [14]:

1506/32

47.0625

In [15]:
215/32

6.71875

In [ ]:
history = model.fit(
    train_generator,
    steps_per_epoch=47,
    batch_size=32,
    validation_data=validation_generator,
    validation_steps=6,
    verbose=1,
    epochs=20,
)

In [ ]:
scores = model.evaluate(test_generator)


In [ ]:
scores


In [ ]:
history

In [ ]:
history.params

In [ ]:
history.history.keys()

In [ ]:
type(history.history['loss'])

In [ ]:
len(history.history['loss'])

In [ ]:
history.history['loss'][:5] # show loss for first 5 epochs

In [ ]:

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

In [ ]:
val_acc

In [ ]:
acc

In [ ]:
EPOCHS = 20

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(range(EPOCHS), acc, label='Training Accuracy')
plt.plot(range(EPOCHS), val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(range(EPOCHS), loss, label='Training Loss')
plt.plot(range(EPOCHS), val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

In [ ]:
import numpy as np


for image_batch, label_batch in test_generator:
    first_image = image_batch[0]
    first_label = int(labels_batch[0])
    
    print("first image to predict")
    plt.imshow(first_image)
    print("actual label:",class_names[first_label])
    
    batch_prediction = model.predict(images_batch)
    print("predicted label:",class_names[np.argmax(batch_prediction[0])])
    
    break

In [ ]:
def predict(model, img):
    img_array = tf.keras.preprocessing.image.img_to_array(images[i])
    img_array = tf.expand_dims(img_array, 0)

    predictions = model.predict(img_array)

    predicted_class = class_names[np.argmax(predictions[0])]
    confidence = round(100 * (np.max(predictions[0])), 2)
    return predicted_class, confidence

In [ ]:
plt.figure(figsize=(15, 15))
for images, labels in test_generator:
    for i in range(9):
        ax = plt.subplot(3, 3, i + 1)
        plt.imshow(images[i])
        
        predicted_class, confidence = predict(model, images[i])
        actual_class = class_names[int(labels[i])] 
        
        plt.title(f"Actual: {actual_class},\n Predicted: {predicted_class}.\n Confidence: {confidence}%")
        
        plt.axis("off")
    break

In [ ]:
model.save("../potatoes1.h5")